name: Health check 

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  
  # schedule:
  #   - cron: '5,10,15,20,25,30,35,40,45,50,55 * * * *'

jobs:
  check-health:
    steps:
      - name: Check health of the deployed app
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-dqlr.onrender.com/health
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false