name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-24.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

  date_job:
    runs-on: ubuntu-24.04
    steps:
      - name: Print date
        run: |
          date

  ls_directory_job:
    runs-on: ubuntu-24.04
    steps:
      - name: List directory
        run: |
          ls -l